// registry — the embedded manifest-hash payload and drift check
// (bee.mjs computeManifestHash / checkManifestDrift).
//
// The payload is the EXACT `JSON.stringify({schema_version, commands})`
// string Node hashes, generated by scripts/export_registry_payload.mjs —
// both runtimes hash identical bytes, so .bee/cache/manifest-hash.json never
// flip-flops between them mid-campaign (contract C1). The freshness test in
// tests/front_door.rs fails loudly when the export step is forgotten.

use crate::fsutil::{read_json, remove_file_if_exists, write_json_atomic, ReadJson};
use crate::state::Bail;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

pub const REGISTRY_PAYLOAD: &str = include_str!("generated/registry_payload.json");

pub fn manifest_hash() -> String {
    let mut hasher = Sha256::new();
    hasher.update(REGISTRY_PAYLOAD.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn cache_hash_path(root: &Path) -> PathBuf {
    root.join(".bee").join("cache").join("manifest-hash.json")
}

fn legacy_hash_path(root: &Path) -> PathBuf {
    root.join(".bee").join("manifest-hash.json")
}

pub struct Drift {
    pub manifest_changed: bool,
    pub hint: &'static str,
}

const HINT: &str = "Command registry content changed since the last bee.mjs call — re-run \"bee --help --json\" to refresh the manifest.";

/// checkManifestDrift (write path — the doctor-only skipWrite branch stays
/// with Node until doctor ports). ISO timestamp matches Date.toISOString().
pub fn check_manifest_drift(root: &Path) -> Result<Drift, Bail> {
    let current = manifest_hash();
    let state_file = cache_hash_path(root);

    let read_prior = |file: &Path| -> Result<Option<Value>, Bail> {
        match read_json(file) {
            ReadJson::Missing => Ok(None),
            ReadJson::Corrupt => Err(Bail::NeedsNode), // Node warns with the V8 message
            ReadJson::Parsed(v) => Ok(Some(v)),
        }
    };
    // readJson(cache, null) || readJson(legacy, null) — null AND falsy parses
    // (0, "", false) fall through to the legacy file in JS; mirror that.
    let is_falsy = |v: &Value| {
        matches!(v, Value::Null | Value::Bool(false))
            || matches!(v, Value::Number(n) if n.as_f64() == Some(0.0))
            || matches!(v, Value::String(s) if s.is_empty())
    };
    let prior = match read_prior(&state_file)? {
        Some(v) if !is_falsy(&v) => Some(v),
        _ => read_prior(&legacy_hash_path(root))?,
    };
    let prior_hash = prior
        .as_ref()
        .and_then(|p| p.get("hash"))
        .and_then(Value::as_str)
        .map(str::to_string);

    let checked_at = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string();
    // Best-effort persistence, exactly like Node's try/catch: a write failure
    // never weakens the comparison already made above.
    if write_json_atomic(&state_file, &json!({"hash": current, "checked_at": checked_at})).is_ok() {
        remove_file_if_exists(&legacy_hash_path(root));
    }

    Ok(Drift {
        manifest_changed: matches!(&prior_hash, Some(h) if h != &current),
        hint: HINT,
    })
}
