// registry — the embedded manifest-hash payload and drift check
// (bee.mjs computeManifestHash / checkManifestDrift).
//
// The payload is the EXACT `JSON.stringify({schema_version, commands})`
// string Node hashes, generated by scripts/export_registry_payload.mjs —
// both runtimes hash identical bytes, so .bee/cache/manifest-hash.json never
// flip-flops between them mid-campaign (contract C1). The freshness test in
// tests/front_door.rs fails loudly when the export step is forgotten.

use crate::fsutil::{read_json, remove_file_if_exists, write_json_atomic, ReadJson};
use crate::state::Bail;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

pub const REGISTRY_PAYLOAD: &str = include_str!("generated/registry_payload.json");

pub fn manifest_hash() -> String {
    let mut hasher = Sha256::new();
    hasher.update(REGISTRY_PAYLOAD.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn cache_hash_path(root: &Path) -> PathBuf {
    root.join(".bee").join("cache").join("manifest-hash.json")
}

fn legacy_hash_path(root: &Path) -> PathBuf {
    root.join(".bee").join("manifest-hash.json")
}

pub struct Drift {
    pub manifest_changed: bool,
    pub hint: &'static str,
}

/// CUTOVER wording change: Node's hint said "since the last bee.mjs call",
/// naming an entry point that no longer exists. It names the command instead.
const HINT: &str = "Command registry content changed since the last bee call — re-run \"bee --help --json\" to refresh the manifest.";

/// checkManifestDrift (write path — the doctor-only skipWrite branch stays
/// with Node until doctor ports). ISO timestamp matches Date.toISOString().
pub fn check_manifest_drift(root: &Path) -> Result<Drift, Bail> {
    let current = manifest_hash();
    let state_file = cache_hash_path(root);

    let read_prior = |file: &Path| -> Result<Option<Value>, Bail> {
        match read_json(file) {
            ReadJson::Missing => Ok(None),
            // CUTOVER: readJson(file, null) warned and returned null, and the
            // caller treated that as "no prior hash recorded" — i.e. exactly
            // the Missing arm. Same fallback, our wording.
            ReadJson::Corrupt => {
                crate::fsutil::warn_corrupt_json(file);
                Ok(None)
            }
            ReadJson::Parsed(v) => Ok(Some(v)),
        }
    };
    // readJson(cache, null) || readJson(legacy, null) — null AND falsy parses
    // (0, "", false) fall through to the legacy file in JS; mirror that.
    let is_falsy = |v: &Value| {
        matches!(v, Value::Null | Value::Bool(false))
            || matches!(v, Value::Number(n) if n.as_f64() == Some(0.0))
            || matches!(v, Value::String(s) if s.is_empty())
    };
    let prior = match read_prior(&state_file)? {
        Some(v) if !is_falsy(&v) => Some(v),
        _ => read_prior(&legacy_hash_path(root))?,
    };
    let prior_hash = prior
        .as_ref()
        .and_then(|p| p.get("hash"))
        .and_then(Value::as_str)
        .map(str::to_string);

    let checked_at = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string();
    // Best-effort persistence, exactly like Node's try/catch: a write failure
    // never weakens the comparison already made above.
    if write_json_atomic(&state_file, &json!({"hash": current, "checked_at": checked_at})).is_ok() {
        remove_file_if_exists(&legacy_hash_path(root));
    }

    Ok(Drift {
        manifest_changed: matches!(&prior_hash, Some(h) if h != &current),
        hint: HINT,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(file: &Path, content: &str) {
        std::fs::create_dir_all(file.parent().unwrap()).unwrap();
        std::fs::write(file, content).unwrap();
    }

    /// CUTOVER: a corrupt cache used to bail to Node. Node's readJson warned
    /// and returned null, and a null prior hash means "nothing recorded yet"
    /// — NOT drift. The native path must reach the same conclusion, and must
    /// still rewrite the cache so the next call is clean.
    #[test]
    fn corrupt_hash_cache_reads_as_no_prior_hash_and_reports_no_drift() {
        let tmp = tempfile::tempdir().unwrap();
        write(&cache_hash_path(tmp.path()), "{broken");
        let drift = check_manifest_drift(tmp.path()).ok().expect("must fail open");
        assert!(!drift.manifest_changed, "an unreadable cache is not drift");
        // The cache was repaired in place by the best-effort write.
        let repaired = std::fs::read_to_string(cache_hash_path(tmp.path())).unwrap();
        assert!(repaired.contains(&manifest_hash()));
    }

    /// A corrupt CACHE still falls through to the legacy file, exactly as
    /// `readJson(cache, null) || readJson(legacy, null)` did.
    #[test]
    fn corrupt_cache_falls_through_to_the_legacy_file() {
        let tmp = tempfile::tempdir().unwrap();
        write(&cache_hash_path(tmp.path()), "{broken");
        write(&legacy_hash_path(tmp.path()), r#"{"hash":"stale-hash"}"#);
        let drift = check_manifest_drift(tmp.path()).ok().unwrap();
        assert!(drift.manifest_changed, "the legacy hash differs — that IS drift");
    }

    /// The hint names the binary, never a script that no longer ships.
    #[test]
    fn drift_hint_names_the_binary() {
        assert!(!HINT.contains(".mjs"), "{HINT}");
        assert!(HINT.contains("since the last bee call"), "{HINT}");
    }
}
