// Black-box tests for the front door AFTER the Node cutover.
//
// Until R6 this file's centrepiece was `output_is_byte_identical_to_node`: it
// ran `node packages/bee/bee.mjs` and the Rust binary over the same argv and
// demanded identical bytes (contract C2). Both halves of that test are gone on
// purpose — the oracle was deleted with the runtime, and C2 was deliberately
// retired at cutover (plans/rust-port.md: the corrupt-JSON paths, the session
// preamble and encodeProjectDir now diverge by design). A comparison against
// an absent oracle is not a weaker test, it is a vacuous one, and a vacuously
// green check is worse than no check.
//
// `embedded_registry_payload_is_fresh` went the same way: it re-exported
// lib/command-registry.mjs under node and byte-compared. The registry payload
// is now generated by `bee dev` and pinned by tests/registry_contracts.rs,
// which reads the embedded bytes directly.
//
// What replaces them is the property that actually matters now that nothing
// sits behind the binary: EVERY argv shape produces an answer. Served,
// refused, or unknown — never silence, never a zero exit with no output.

use assert_cmd::Command;

#[test]
fn rs_info_reports_rust_runtime_and_no_fallback() {
    let out = Command::cargo_bin("bee").unwrap().arg("rs-info").assert().success();
    let stdout = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    let v: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(v["runtime"], "rust");
    assert!(v["ported"].as_array().is_some());
    // The cutover's one-line summary: there is nothing behind this binary.
    assert_eq!(v["fallback"], serde_json::Value::Null);
}

/// The cutover's core invariant. Before R6 an argv shape no probe claimed was
/// handed to `node bee.mjs`; with that gone the SAME code path would exit 0
/// having printed nothing, which reads to every caller — human, script, hook
/// or CI — as "the command succeeded and did nothing". It must refuse instead.
#[test]
fn an_unserved_argv_shape_refuses_out_loud() {
    let tmp = tempfile::tempdir().unwrap();
    let out = Command::cargo_bin("bee")
        .unwrap()
        .arg("definitely-not-a-bee-verb")
        .current_dir(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1), "an unserved shape must exit non-zero");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("bee: unknown command"),
        "the refusal must name itself — and for an argv nothing in the registry spells, the \
         name of the problem is 'unknown command', not the old catch-all 'unsupported command \
         shape' (which also fired for a real command missing a flag). stderr was: {stderr}"
    );
    // The refusal points somewhere useful rather than dead-ending.
    assert!(stderr.contains("bee --help"), "stderr was: {stderr}");
    assert!(out.stdout.is_empty(), "text-mode refusals belong on stderr");
}

/// …and a caller that asked for JSON gets JSON, not an unparseable empty
/// document. A script piping `bee … --json` into a parser must fail loudly on
/// the refusal, not crash on nothing.
#[test]
fn an_unserved_argv_shape_refuses_in_json_when_json_was_requested() {
    let tmp = tempfile::tempdir().unwrap();
    let out = Command::cargo_bin("bee")
        .unwrap()
        .args(["definitely-not-a-bee-verb", "--json"])
        .current_dir(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let v: serde_json::Value = serde_json::from_str(stdout.trim())
        .unwrap_or_else(|e| panic!("not JSON: {stdout:?} ({e})"));
    assert!(v["error"].as_str().unwrap().contains("bee: unknown command"));
    // …and the machine-readable class beside it, so a caller branches on
    // `kind` instead of regex-matching prose.
    assert_eq!(v["kind"], "unknown_command");
}

/// A bare `bee` names itself too. The empty argv used to reach Node's
/// dispatcher, which printed its own usage; there is no argv here to quote, so
/// the refusal has to stand on its own.
#[test]
fn a_bare_invocation_refuses_out_loud() {
    let tmp = tempfile::tempdir().unwrap();
    let out = Command::cargo_bin("bee").unwrap().current_dir(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(1));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("(no command given)"), "stderr was: {stderr}");
}

/// `--help` is the surface the refusal points at, so it had better work with
/// no repo and no state — it renders entirely from the embedded registry.
#[test]
fn help_works_with_no_repo() {
    let tmp = tempfile::tempdir().unwrap();
    for args in [vec!["--help"], vec!["--help", "--all"], vec!["--help", "--json"]] {
        let out = Command::cargo_bin("bee")
            .unwrap()
            .args(&args)
            .current_dir(tmp.path())
            .output()
            .unwrap();
        assert!(out.status.success(), "{args:?} exited {:?}", out.status.code());
        assert!(!out.stdout.is_empty(), "{args:?} printed nothing");
    }
}
