// bee dev render-hook-manifests — the hook catalog and its three projections.
//
// PROVENANCE: packages/bee/hooks/catalog.mjs (RUNTIMES / TARGETS / CATALOG /
// repoCommand / pluginCommand / windowsBootstrap / renderProjection /
// renderProjectionText / EVENTS / ALLOWED_DIFFERENCES), plus its drift check
// in hooks/test_hook_contracts.mjs. Both are deleted at the R6 cutover; this
// module is where they land.
//
// WHY IT WAS PORTED RATHER THAN KEPT. catalog.mjs was the last Node file with
// a live job: it is the single authority for three checked-in generated files
// and there was never a render SCRIPT — the files were regenerated by calling
// `renderProjectionText` from a test, and the drift check was the gate. Two of
// the three options at cutover were worse than this one:
//
//   * Keep catalog.mjs as "the one surviving Node file". Then `node` remains
//     a hard requirement for anyone who edits a hook, the deletion is not a
//     deletion, and the repo keeps a second language for 400 lines.
//   * Hand-maintain the three JSON files. They carry a 9-line shell command
//     repeated ~11 times per file, in three different escapings; the ONLY
//     reason they have never drifted is that a generator owned them.
//
// So the catalog is Rust now, `bee dev render-hook-manifests --write`
// regenerates, `--check` is the drift gate, and `hook_manifests_match_disk`
// below runs that gate inside `cargo test` — the same place every other
// contract in this tree is enforced.
//
// The Codex REPO projection is not re-derived here: it calls
// onboard::hooks_wiring's own `codex_hook_command` / `codex_hook_command_
// windows`. Before the cutover those two renderers were deliberate
// duplicates (onboard's HOST projection pointed at `.bee/bin/hooks/`, the
// catalog's at the same place but with a binary arm), and the "two renderers,
// one generated file" trap that comment in onboard_bee.mjs warns about was
// real — a release actually broke on it. Rewiring both to the binary made
// them byte-identical, so they are now ONE renderer and the trap cannot fire
// at all.

use super::{bee_source_root, rel_platform};
use crate::jsjson;
use crate::onboard::hooks_wiring::{codex_hook_command, codex_hook_command_windows};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Runtime {
    Claude,
    Codex,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// The hook file ships inside the plugin root, so the host exports
    /// `${CLAUDE_PLUGIN_ROOT}` and the command resolves against it.
    Plugin,
    /// The source-repository projection (`.codex/hooks.json`). Codex loads a
    /// project's own hooks file with NO plugin root exported, so the command
    /// resolves the git root from the session cwd instead.
    Repo,
}

/// A catalog row: one hook on one event, for one or both runtimes.
struct Entry {
    script: &'static str,
    status_message: &'static str,
}

struct Group {
    claude: bool,
    codex: bool,
    matcher: Option<&'static str>,
    hooks: &'static [Entry],
}

struct Event {
    name: &'static str,
    groups: &'static [Group],
}

/// (renders for claude, renders for codex)
const BOTH: (bool, bool) = (true, true);
const CLAUDE_ONLY: (bool, bool) = (true, false);
const CODEX_ONLY: (bool, bool) = (false, true);

macro_rules! group {
    ($rt:expr, $matcher:expr, [$(($s:expr, $m:expr)),* $(,)?]) => {
        Group {
            claude: $rt.0,
            codex: $rt.1,
            matcher: $matcher,
            hooks: &[$(Entry { script: $s, status_message: $m }),*],
        }
    };
}

/// One entry per lifecycle event bee wires. Runtime differences are explicit
/// data, never hand-maintained projection drift — see ALLOWED_DIFFERENCES.
const CATALOG: &[Event] = &[
    Event {
        name: "SessionStart",
        groups: &[group!(
            BOTH,
            Some("startup|resume|clear|compact"),
            [("bee-session-init.mjs", "bee: session bootstrap")]
        )],
    },
    Event {
        name: "UserPromptSubmit",
        groups: &[group!(BOTH, None, [("bee-prompt-context.mjs", "bee: phase reminder")])],
    },
    Event {
        name: "PreToolUse",
        groups: &[
            group!(
                BOTH,
                Some("Edit|Write|MultiEdit|Bash|Read|Glob|Grep|AskUserQuestion"),
                [("bee-write-guard.mjs", "bee: write guard")]
            ),
            // Claude dispatches subagents as Agent|Task…
            group!(
                CLAUDE_ONLY,
                Some("Agent|Task"),
                [("bee-model-guard.mjs", "bee: model-tier guard")]
            ),
            // …Codex exposes the same act as the tool name "spawn_agent"
            // (codex-cli 0.144.4, capability-matrix row D1). A MATCHER
            // difference, not a capability gap: same handler, Codex branch.
            group!(
                CODEX_ONLY,
                Some("spawn_agent"),
                [("bee-model-guard.mjs", "bee: model-tier guard")]
            ),
        ],
    },
    Event {
        name: "PostToolUse",
        groups: &[
            // Superset, never a swap: update_plan is Codex's native plan tool;
            // TaskCreate/TaskUpdate/TodoWrite stay wired for Claude.
            group!(
                BOTH,
                Some("update_plan|TaskCreate|TaskUpdate|TodoWrite"),
                [("bee-state-sync.mjs", "bee: state sync")]
            ),
            // No matcher = every tool. Passive measurement only; this hook can
            // never deny or block.
            group!(BOTH, None, [("bee-tools-logger.mjs", "bee: tools logger")]),
        ],
    },
    Event {
        name: "SubagentStart",
        groups: &[group!(
            CODEX_ONLY,
            None,
            [("bee-codex-subagent-audit.mjs", "bee: subagent start audit")]
        )],
    },
    Event {
        name: "SubagentStop",
        groups: &[
            group!(
                BOTH,
                None,
                [
                    ("bee-state-sync.mjs", "bee: state sync"),
                    ("bee-chain-nudge.mjs", "bee: chain nudge"),
                ]
            ),
            group!(
                CODEX_ONLY,
                None,
                [("bee-codex-subagent-audit.mjs", "bee: subagent stop audit")]
            ),
        ],
    },
    Event {
        name: "PreCompact",
        groups: &[group!(
            BOTH,
            None,
            [("bee-session-close.mjs", "bee: pre-compact flush check")]
        )],
    },
    Event {
        name: "Stop",
        groups: &[group!(
            BOTH,
            None,
            [
                ("bee-state-sync.mjs", "bee: state sync"),
                ("bee-session-close.mjs", "bee: session close check"),
            ]
        )],
    },
];

/// The rendered command's hook NAME. The catalog still keys on the historical
/// `bee-<name>.mjs` spelling because that string is the join between this
/// table, the write guard's recognizer and every historical hooks.json a
/// re-render has to REPLACE; the rendered command names only `<name>`.
fn hook_name(script: &str) -> &str {
    script.strip_prefix("bee-").unwrap_or(script).strip_suffix(".mjs").unwrap_or(script)
}

/// The diagnostic a host sees when it carries no binary. Same text the onboard
/// projection uses — visible fail-open, never silence (spec R2).
const BINARY_MISSING: &str = "bee: hook binary missing (.bee/bin/bee)";

/// pluginCommand. The plugin target runs with `${CLAUDE_PLUGIN_ROOT}`
/// exported, so it needs no root resolve — but the binary it launches lives in
/// the HOST repo (machine-local by decision 1f4262ca; a plugin root cloned
/// from a marketplace never carries one), which Claude Code exports as
/// `$CLAUDE_PROJECT_DIR`. The plugin root is probed second, for a source
/// checkout used as its own plugin root that has been built in place.
///
/// Rendered as ONE `;`-joined line, never newline-joined: a single line is
/// unambiguous under every hook runner, and this projection is the
/// widest-blast-radius surface bee ships.
fn plugin_command(script: &str) -> String {
    let name = hook_name(script);
    let candidates = [
        "\"$CLAUDE_PROJECT_DIR/.bee/bin/bee\"",
        "\"$CLAUDE_PROJECT_DIR/.bee/bin/bee.exe\"",
        "\"${CLAUDE_PLUGIN_ROOT}/.bee/bin/bee\"",
        "\"${CLAUDE_PLUGIN_ROOT}/.bee/bin/bee.exe\"",
    ]
    .join(" ");
    // …then the main checkout, for a linked worktree — see main_checkout_arm.
    let arm = crate::onboard::hooks_wiring::main_checkout_arm(name, "\"$CLAUDE_PROJECT_DIR\"", "");
    format!(
        "for b in {candidates}; do [ -x \"$b\" ] && exec \"$b\" hook {name}; done; {arm}; \
         echo \"{BINARY_MISSING}\" >&2; exit 0"
    )
}

fn command_for(script: &str, target: Target) -> String {
    match target {
        Target::Repo => codex_hook_command(script),
        Target::Plugin => plugin_command(script),
    }
}

/// Render one projection as the plain hooks.json object — no runtime/target
/// metadata leaks into the output, only the matcher/hooks shape Claude Code
/// and Codex already load.
pub fn render_projection(runtime: Runtime, target: Target) -> Value {
    let mut hooks = Map::new();
    for event in CATALOG {
        let mut rendered: Vec<Value> = Vec::new();
        for g in event.groups {
            let wanted = match runtime {
                Runtime::Claude => g.claude,
                Runtime::Codex => g.codex,
            };
            if !wanted {
                continue;
            }
            let mut out = Map::new();
            if let Some(m) = g.matcher {
                out.insert("matcher".into(), json!(m));
            }
            let entries: Vec<Value> = g
                .hooks
                .iter()
                .map(|h| {
                    let mut e = Map::new();
                    e.insert("type".into(), json!("command"));
                    e.insert("command".into(), json!(command_for(h.script, target)));
                    // commandWindows is CODEX-REPO-ONLY: the Codex plugin
                    // manifest omits codex hooks, and Claude's hook schema has
                    // no such field.
                    if runtime == Runtime::Codex && target == Target::Repo {
                        e.insert(
                            "commandWindows".into(),
                            json!(codex_hook_command_windows(h.script)),
                        );
                    }
                    e.insert("statusMessage".into(), json!(h.status_message));
                    Value::Object(e)
                })
                .collect();
            out.insert("hooks".into(), Value::Array(entries));
            rendered.push(Value::Object(out));
        }
        if !rendered.is_empty() {
            hooks.insert(event.name.to_string(), Value::Array(rendered));
        }
    }
    json!({ "hooks": Value::Object(hooks) })
}

/// Deterministic, byte-stable text: 2-space indent plus exactly one trailing
/// newline — `JSON.stringify(x, null, 2) + "\n"`, matching the checked-in
/// formatting so the drift check is a byte compare.
pub fn render_projection_text(runtime: Runtime, target: Target) -> String {
    format!("{}\n", jsjson::stringify_pretty(&render_projection(runtime, target)))
}

/// The three generated files, relative to the bee source root.
pub fn projections() -> [(&'static str, Runtime, Target); 3] {
    [
        ("packages/bee/hooks/claude-hooks.json", Runtime::Claude, Target::Plugin),
        ("packages/bee/hooks/hooks.json", Runtime::Codex, Target::Plugin),
        (".codex/hooks.json", Runtime::Codex, Target::Repo),
    ]
}

fn abs(root: &Path, rel: &str) -> PathBuf {
    rel.split('/').fold(root.to_path_buf(), |p, seg| p.join(seg))
}

pub fn run(flags: &[&str]) -> Option<ExitCode> {
    let (check, write) = match flags {
        ["--check"] => (true, false),
        ["--write"] => (false, true),
        _ => return None,
    };
    let root = bee_source_root()?;
    let mut stale: Vec<String> = Vec::new();
    let mut wrote: Vec<PathBuf> = Vec::new();
    for (rel, runtime, target) in projections() {
        let path = abs(&root, rel);
        let want = render_projection_text(runtime, target);
        let have = std::fs::read_to_string(&path).unwrap_or_default();
        if have == want {
            continue;
        }
        if write {
            if let Some(dir) = path.parent() {
                let _ = std::fs::create_dir_all(dir);
            }
            if std::fs::write(&path, &want).is_err() {
                eprintln!("render-hook-manifests: cannot write {}", path.display());
                return Some(ExitCode::FAILURE);
            }
            wrote.push(path);
        } else {
            stale.push(rel.to_string());
        }
    }
    if check {
        if stale.is_empty() {
            println!("hook manifests: 3 projections in sync");
            return Some(ExitCode::SUCCESS);
        }
        eprintln!(
            "hook manifests: {} projection(s) DRIFTED from the catalog: {}. FIX: bee dev render-hook-manifests --write",
            stale.len(),
            stale.join(", ")
        );
        return Some(ExitCode::FAILURE);
    }
    for p in &wrote {
        println!("WROTE {}", rel_platform(&root, p));
    }
    println!("hook manifests: {} written, {} already in sync", wrote.len(), 3 - wrote.len());
    Some(ExitCode::SUCCESS)
}

// ─── ALLOWED_DIFFERENCES ───────────────────────────────────────────────────
//
// The approved differences between the two rendered plugin projections.
// Anything not covered here is drift and fails `projections_differ_only_where_
// approved` below.
//
//   model-tier-guard-claude-only   PreToolUse "Agent|Task"  bee-model-guard
//   model-tier-guard-codex-spawn   PreToolUse "spawn_agent" bee-model-guard
//   subagent-start-audit-codex-only  SubagentStart  bee-codex-subagent-audit
//   subagent-stop-audit-codex-only   SubagentStop   bee-codex-subagent-audit
//
// The first two are one capability on two tool names. The last two exist
// because SubagentStart/Stop are events only Codex exposes today; bee records
// bounded audit evidence there and claims no pre-spawn authority.

#[cfg(test)]
mod tests {
    use super::*;

    /// The drift gate, moved out of hooks/test_hook_contracts.mjs. The three
    /// checked-in files are generated; a hand edit to any of them, or a
    /// catalog change without a re-render, fails here.
    #[test]
    fn hook_manifests_match_disk() {
        let Some(root) = bee_source_root() else {
            eprintln!("SKIP (env-limited: not inside a bee source checkout) hook_manifests_match_disk");
            return;
        };
        for (rel, runtime, target) in projections() {
            let path = abs(&root, rel);
            let have = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("{rel} is generated and must exist: {e}"));
            assert_eq!(
                have,
                render_projection_text(runtime, target),
                "{rel} drifted from the catalog. FIX: bee dev render-hook-manifests --write"
            );
        }
    }

    /// CUTOVER: no projection may name a `.mjs` wrapper or `node` in a
    /// position that LAUNCHES something. There is nothing left to launch, so a
    /// surviving arm would be a hook that silently does nothing on every
    /// event.
    ///
    /// This test used to carry ONE exemption — the Codex Windows `node -e`
    /// bootstrap — on the reasoning that the ban on `$`/`%`/backtick also bans
    /// command substitution, so the command text could not ask git for the
    /// repo root and therefore needed an interpreter to do the lookup. The
    /// exemption is gone with the thing it excused: a `!`-prefixed git alias
    /// is run from the repo top level, so the root never has to be COMPUTED,
    /// only relied on (`onboard::hooks_wiring::codex_hook_command_windows`).
    /// The assertion is now unconditional — Node appears in no projection, on
    /// no transport.
    #[test]
    fn no_projection_launches_a_wrapper_or_node_on_any_transport() {
        for (rel, runtime, target) in projections() {
            let v = render_projection(runtime, target);
            let hooks = v["hooks"].as_object().unwrap();
            for (event, groups) in hooks {
                for g in groups.as_array().unwrap() {
                    for h in g["hooks"].as_array().unwrap() {
                        let command = h["command"].as_str().unwrap();
                        assert!(
                            !command.contains(".mjs"),
                            "{rel} {event}: command still names a wrapper: {command}"
                        );
                        assert!(
                            !command.contains("node "),
                            "{rel} {event}: command still launches node: {command}"
                        );
                        assert!(
                            command.contains(" hook "),
                            "{rel} {event}: command does not launch the binary: {command}"
                        );
                        if let Some(win) = h.get("commandWindows").and_then(|w| w.as_str()) {
                            assert!(
                                !win.contains(".mjs"),
                                "{rel} {event}: commandWindows still names a wrapper: {win}"
                            );
                            assert!(
                                !win.contains("node"),
                                "{rel} {event}: commandWindows still launches node: {win}"
                            );
                            assert!(
                                win.contains(" hook "),
                                "{rel} {event}: commandWindows does not launch the binary: {win}"
                            );
                        }
                    }
                }
            }
        }
    }

    /// A host with no binary must SEE that, on EVERY transport. A silent
    /// exit 0 is how a guard stops guarding without anyone noticing.
    ///
    /// This used to search `render_projection_text` - the whole rendered
    /// document - for the diagnostic. That is one string containing both
    /// transports, so the POSIX `command` arm satisfied the search while
    /// `commandWindows` bailed with a bare `process.exit(0)`. Every Codex
    /// session on Windows whose repo or binary could not be resolved lost the
    /// write guard in silence, and this test was green throughout. It now
    /// checks each command string on its own.
    #[test]
    fn every_projection_fails_open_visibly() {
        let mut checked = 0usize;
        for (rel, runtime, target) in projections() {
            let v = render_projection(runtime, target);
            for (event, groups) in v["hooks"].as_object().unwrap() {
                for g in groups.as_array().unwrap() {
                    for h in g["hooks"].as_array().unwrap() {
                        for field in ["command", "commandWindows"] {
                            let Some(cmd) = h.get(field).and_then(|c| c.as_str()) else {
                                continue;
                            };
                            checked += 1;
                            assert!(
                                cmd.contains(BINARY_MISSING),
                                "{rel} {event} {field}: bails without a no-binary diagnostic: {cmd}"
                            );
                        }
                    }
                }
            }
        }
        assert!(checked > 20, "only {checked} command strings walked - the scan went vacuous");

        // ...and the repo transport keeps its own no-git-root arm, on both
        // of its transports.
        let repo = render_projection(Runtime::Codex, Target::Repo);
        for (event, groups) in repo["hooks"].as_object().unwrap() {
            for g in groups.as_array().unwrap() {
                for h in g["hooks"].as_array().unwrap() {
                    for field in ["command", "commandWindows"] {
                        let Some(cmd) = h.get(field).and_then(|c| c.as_str()) else { continue };
                        assert!(
                            cmd.contains("bee: hook transport unavailable (no git root)"),
                            "codex repo {event} {field}: no unresolvable-root diagnostic: {cmd}"
                        );
                    }
                }
            }
        }
    }

    /// The two PLUGIN projections may differ only where ALLOWED_DIFFERENCES
    /// says. Compared as (event, matcher, script) triples so a command-string
    /// change can never masquerade as an approved difference.
    #[test]
    fn projections_differ_only_where_approved() {
        fn triples(runtime: Runtime) -> Vec<(String, String, String)> {
            let v = render_projection(runtime, Target::Plugin);
            let mut out = Vec::new();
            for (event, groups) in v["hooks"].as_object().unwrap() {
                for g in groups.as_array().unwrap() {
                    let matcher =
                        g.get("matcher").and_then(|m| m.as_str()).unwrap_or("*").to_string();
                    for h in g["hooks"].as_array().unwrap() {
                        // The command carries the hook name; recover it.
                        let c = h["command"].as_str().unwrap();
                        let name = c
                            .split(" hook ")
                            .nth(1)
                            .and_then(|t| t.split(';').next())
                            .and_then(|t| t.split_whitespace().next())
                            .unwrap()
                            .to_string();
                        out.push((event.clone(), matcher.clone(), name));
                    }
                }
            }
            out.sort();
            out
        }
        let claude = triples(Runtime::Claude);
        let codex = triples(Runtime::Codex);
        let approved: &[(&str, &str, &str)] = &[
            ("PreToolUse", "Agent|Task", "model-guard"),
            ("PreToolUse", "spawn_agent", "model-guard"),
            ("SubagentStart", "*", "codex-subagent-audit"),
            ("SubagentStop", "*", "codex-subagent-audit"),
        ];
        let is_approved = |t: &(String, String, String)| {
            approved.iter().any(|(e, m, s)| *e == t.0 && *m == t.1 && *s == t.2)
        };
        for t in claude.iter().filter(|t| !codex.contains(t)) {
            assert!(is_approved(t), "unapproved claude-only row: {t:?}");
        }
        for t in codex.iter().filter(|t| !claude.contains(t)) {
            assert!(is_approved(t), "unapproved codex-only row: {t:?}");
        }
    }

    /// The Codex REPO projection and onboard's HOST projection are now the
    /// SAME renderer. This pins that: if someone re-forks them, the trap that
    /// broke a release (two renderers, one generated file) comes back.
    #[test]
    fn the_codex_repo_and_host_projections_share_one_renderer() {
        let from_catalog = command_for("bee-write-guard.mjs", Target::Repo);
        let from_onboard = crate::onboard::hooks_wiring::codex_hook_command("bee-write-guard.mjs");
        assert_eq!(from_catalog, from_onboard);
    }
}
