#!/usr/bin/env node
// Generator for the two committed plugin skill-route trees (D9 LOCKED
// topology, slice-3 rev3, cell cnr2-12):
//
//   .claude-plugin/skills/ = render(canonical skills/, "claude")
//   .codex-plugin/skills/  = render(canonical skills/, "codex")
//
// Both trees are generated ONLY through the cnr2-9 renderer
// (renderSkillBytes) — never hand-copied. Package-time rendering was
// REJECTED (decision logged): these trees are committed, inspectable, and
// regenerated by re-running this script whenever canonical skills/ content
// changes. Today no skill file carries a runtime marker, so both trees are
// byte-identical to skills/ — no visible change, machinery + proof only.
//
// Whole-tree marker grammar is validated BEFORE any write (mirrors
// onboard_bee.mjs's validateSkillTreeMarkers): a malformed marker anywhere
// refuses the entire regeneration with zero writes.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

import {
  renderSkillBytes,
  validateSkillMarkers,
  RENDER_RUNTIMES,
  RENDER_SIDECAR,
  buildRenderSidecar,
} from "../packages/bee/scripts/onboard_bee.mjs";
import { withStoreLock, isPidAlive } from "../packages/bee/lib/lock.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, "..");
const SOURCE_ROOT = path.join(REPO_ROOT, "skills");
const SKILL_DIR_RE = /^bee-/;

export const TARGET_ROOTS = {
  claude: path.join(REPO_ROOT, ".claude-plugin", "skills"),
  codex: path.join(REPO_ROOT, ".codex-plugin", "skills"),
};

function listBeeSkillDirs() {
  return fs
    .readdirSync(SOURCE_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.isSymbolicLink() && SKILL_DIR_RE.test(entry.name))
    .map((entry) => entry.name)
    .sort();
}

// Walk one skill dir under SOURCE_ROOT. A symlink anywhere refuses loudly —
// mirrors onboard_bee.mjs's walkSkillTree symlink discipline (a symlinked
// skill dir is plausibly a live checkout; never write through it).
function walkFiles(dir, relPrefix = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
    const abs = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`render_plugin_skill_trees: symlink forbidden in skill source: ${abs}`);
    }
    if (entry.isDirectory()) {
      out.push(...walkFiles(abs, rel));
    } else if (entry.isFile()) {
      out.push({ rel, abs });
    } else {
      throw new Error(`render_plugin_skill_trees: unsupported entry: ${abs}`);
    }
  }
  return out;
}

/** Every canonical bee-* skill file as [{ skillRel, abs }], sorted. */
export function canonicalFiles() {
  const files = [];
  for (const name of listBeeSkillDirs()) {
    for (const { rel, abs } of walkFiles(path.join(SOURCE_ROOT, name))) {
      files.push({ skillRel: `${name}/${rel}`, abs });
    }
  }
  return files;
}

/** Whole-tree marker grammar gate: non-empty means refuse, zero writes. */
export function validateWholeTree(files) {
  const errors = [];
  for (const { skillRel, abs } of files) {
    const text = fs.readFileSync(abs, "utf8");
    for (const e of validateSkillMarkers(text)) errors.push(`${skillRel}: ${e}`);
  }
  return errors;
}

/** render(canonical, runtime) as a Map<skillRel, Buffer>. */
export function renderTree(runtime, files) {
  const rendered = new Map();
  for (const { skillRel, abs } of files) {
    rendered.set(skillRel, renderSkillBytes(fs.readFileSync(abs), runtime));
  }
  return rendered;
}

// rendered: Map<"skillName/relPath", Buffer> (renderTree's output) -> one
// buildRenderSidecar entry per skill: {name, files: Map<relPath, sha256hex>}.
// Per-file hashes are sha256 of the RENDERED bytes already produced by
// renderTree, so the sidecar reflects exactly what writeTree is about to put
// on disk for this runtime (D7/D9).
function groupRenderedBySkill(rendered) {
  const bySkill = new Map();
  for (const [skillRel, bytes] of rendered) {
    const slash = skillRel.indexOf("/");
    const name = skillRel.slice(0, slash);
    const rel = skillRel.slice(slash + 1);
    if (!bySkill.has(name)) bySkill.set(name, new Map());
    bySkill.get(name).set(rel, crypto.createHash("sha256").update(bytes).digest("hex"));
  }
  return [...bySkill.entries()].map(([name, files]) => ({ name, files }));
}

export function sidecarObject(runtime, rendered) {
  return buildRenderSidecar(runtime, groupRenderedBySkill(rendered));
}

export function sidecarBytes(runtime, rendered) {
  return Buffer.from(`${JSON.stringify(sidecarObject(runtime, rendered), null, 2)}\n`, "utf8");
}

// Concurrency safety (cell cs-3): two `node render_plugin_skill_trees.mjs`
// runs firing at once used to race on this exact rmSync-whole-dir + plain
// per-file-write loop — a later run's rmSync could fire mid-way through an
// earlier run's write loop (ENOTEMPTY when files reappear under an
// in-progress delete, or a torn tree with files missing/interleaved from
// both runs). The fix has two parts:
//   1. main() wraps the render+write of BOTH plugin trees in ONE
//      withStoreLock(REPO_ROOT, 'plugin-render') critical section, so only
//      one process is ever inside writeTree at a time system-wide.
//   2. writeTree itself renders into a fresh tmp SIBLING dir (never touching
//      targetRoot), writes the sidecar there too (pre-swap), then swaps via
//      two renames — the only window where targetRoot is observably
//      mid-change shrinks from "the whole write loop" to two atomic
//      rename() syscalls. This also means a crash mid-render leaves the
//      previous committed tree intact rather than half-deleted.
const TMP_STALE_MS = 5 * 60 * 1000; // 5 minutes: presumed a crashed prior run, never a slow one

function randomSuffix() {
  return crypto.randomBytes(6).toString("hex");
}

// Startup hygiene: remove crash-leaked '<base>.tmp-*' AND '<base>.old-*'
// sibling dirs a prior run left behind (tree-hygiene D3 — the render's swap
// backup dirs get the same sweep its tmp dirs already had). Each dir's own
// name embeds the pid that created it (`${base}.tmp-${pid}-${random}` /
// `${base}.old-${pid}-${random}`), so removability is decided by LIVE-PID
// DISCIPLINE first: a dir whose owning pid is proven alive (isPidAlive) is
// never touched, no matter its age — that is exactly a concurrent run's own
// in-progress tmp dir or backup. Only once the owning pid is confirmed dead
// is the dir swept, immediately, regardless of age. A dir whose pid segment
// cannot be parsed at all (should not happen for anything this script itself
// created) falls back to the original age-based staleness signal rather than
// ever guessing "dead". This cleanup runs before acquiring the
// 'plugin-render' lock, deliberately: a leaked dir from a dead pid must not
// require the lock to clean up.
const SWAP_DIR_PREFIXES = ["tmp-", "old-"];

function isSwapDirRemovable(entryName, prefix, stat) {
  const pidMatch = entryName.match(new RegExp(`\\.${prefix}(\\d+)-`));
  if (pidMatch) {
    return !isPidAlive(Number(pidMatch[1]));
  }
  return Date.now() - stat.mtimeMs > TMP_STALE_MS;
}

export function cleanStaleTmpDirs(targetRoot) {
  const parent = path.dirname(targetRoot);
  const base = path.basename(targetRoot);
  let entries;
  try {
    entries = fs.readdirSync(parent, { withFileTypes: true });
  } catch {
    return; // parent doesn't exist yet — nothing to clean
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const prefix = SWAP_DIR_PREFIXES.find((p) => entry.name.startsWith(`${base}.${p}`));
    if (!prefix) continue;
    const abs = path.join(parent, entry.name);
    let stat;
    try {
      stat = fs.statSync(abs);
    } catch {
      continue; // vanished between readdir and stat — fine, nothing to do
    }
    if (isSwapDirRemovable(entry.name, prefix, stat)) {
      fs.rmSync(abs, { recursive: true, force: true });
    }
  }
}

// Render `rendered` into a tmp sibling dir (sidecar included, pre-swap),
// then swap it into place via renames. Caller MUST hold
// withStoreLock(REPO_ROOT, 'plugin-render') — see main().
function writeTree(targetRoot, rendered, runtime) {
  const parent = path.dirname(targetRoot);
  const base = path.basename(targetRoot);
  const tmpRoot = path.join(parent, `${base}.tmp-${process.pid}-${randomSuffix()}`);
  fs.rmSync(tmpRoot, { recursive: true, force: true });
  fs.mkdirSync(tmpRoot, { recursive: true });
  // Set only once the swap has moved the previous tree aside; cleared back to
  // null once it has been removed. Tracked outside the try body so `finally`
  // — not just the success path — is what removes it (tree-hygiene D3): a
  // crash anywhere after the swap succeeds no longer leaks the backup dir.
  let backupRoot = null;
  try {
    for (const [rel, bytes] of rendered) {
      const dest = path.join(tmpRoot, ...rel.split("/"));
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, bytes);
    }
    fs.writeFileSync(path.join(tmpRoot, RENDER_SIDECAR), sidecarBytes(runtime, rendered));

    const existed = fs.existsSync(targetRoot);
    if (existed) {
      backupRoot = path.join(parent, `${base}.old-${process.pid}-${randomSuffix()}`);
      fs.renameSync(targetRoot, backupRoot);
    }
    try {
      fs.renameSync(tmpRoot, targetRoot);
    } catch (error) {
      // Swap failed partway — restore the previous tree rather than leaving
      // targetRoot missing.
      if (backupRoot) {
        fs.renameSync(backupRoot, targetRoot);
        backupRoot = null; // restored — nothing left for finally to remove
      }
      throw error;
    }
  } finally {
    // Runs on every exit path (success or thrown error): tmpRoot removal is a
    // no-op once renamed away; backupRoot, when still set, means the swap
    // committed but cleanup had not yet run — removing it here rather than
    // only on the old success path closes the leak window between the swap
    // and cleanup.
    fs.rmSync(tmpRoot, { recursive: true, force: true });
    if (backupRoot) fs.rmSync(backupRoot, { recursive: true, force: true });
  }
}

async function main() {
  const files = canonicalFiles();
  const errors = validateWholeTree(files);
  if (errors.length) {
    console.error(`render_plugin_skill_trees: refused (marker grammar):\n${errors.join("\n")}`);
    process.exit(1);
  }
  for (const runtime of RENDER_RUNTIMES) {
    cleanStaleTmpDirs(TARGET_ROOTS[runtime]);
  }
  await withStoreLock(REPO_ROOT, "plugin-render", () => {
    for (const runtime of RENDER_RUNTIMES) {
      const rendered = renderTree(runtime, files);
      writeTree(TARGET_ROOTS[runtime], rendered, runtime);
      console.log(
        `WROTE ${path.relative(REPO_ROOT, TARGET_ROOTS[runtime])}: ${rendered.size} file(s) + ${RENDER_SIDECAR}`,
      );
    }
  });
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((error) => {
    console.error(`render_plugin_skill_trees: ${(error && error.stack) || error}`);
    process.exit(1);
  });
}
