//! status_readers_a — the single integration target for rust-port-13's
//! status-read spine (CONTEXT.md D3/D5): `read_backlog_counts`
//! (`.bee/bin/lib/backlog.mjs` `readBacklogCounts`), `capture_queue`
//! (`.bee/bin/lib/capture.mjs` `captureQueue`), `active_decisions`
//! (`.bee/bin/lib/decisions.mjs` `activeDecisions`), and the cells.mjs
//! status helpers (`archived_totals`, `ready_cells`, `scribing_debt`,
//! `global_scribing_debt`, `tier_mix`, `ceiling_scarcity_warning`). Run via
//! `cargo test --manifest-path crates/Cargo.toml -p bee-core --test
//! status_readers_a` (this cell's own `verify`).
//!
//! ORACLE DISCIPLINE (cell must-have): every reader here is diffed against
//! the REAL, FROZEN mjs module — never this file's author's reading of the
//! mjs source alone — via the file-based node driver
//! `tests/support/status_readers_a_oracle.mjs` (same pattern as
//! `fsutil_oracle.rs`, rust-port-5). Fixtures come from two sources:
//!
//! - a host-real-shaped store, generated by the CURRENT already-built
//!   `queen-bench --generate` binary (rust-port-2/rust-port-19, owned by a
//!   concurrent worker this wave — invoked as a fixed prebuilt artifact,
//!   never rebuilt or edited from here);
//! - hand-written edge fixtures: an empty store, corrupt/truncated jsonl
//!   tails, and unknown-extra-field round-trips.
//!
//! Every path used below is a fresh `tempfile::tempdir()` — never this
//! repo's own live `.bee/` store (prohibition: "tests never touch the live
//! .bee/ store").

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use serde_json::{json, Value};

use bee_core::cells;

// ─── oracle driver plumbing ─────────────────────────────────────────────

fn oracle_script() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/support/status_readers_a_oracle.mjs")
}

/// Runs `status_readers_a_oracle.mjs <op> <root>` with `args` (if any)
/// JSON-encoded on stdin, and parses stdout as JSON. Panics loudly on a
/// non-zero exit or unparseable stdout — an oracle failure is never
/// swallowed into a false pass.
fn run_oracle(op: &str, root: &Path, args: Option<Value>) -> Value {
    let mut cmd = Command::new("node");
    cmd.arg(oracle_script()).arg(op).arg(root);
    cmd.stdin(Stdio::piped());
    cmd.stdout(Stdio::piped());
    cmd.stderr(Stdio::piped());
    let mut child = cmd.spawn().expect("failed to spawn node status_readers_a_oracle driver — is `node` on PATH?");
    {
        let mut stdin = child.stdin.take().expect("child stdin");
        let payload = args.map(|v| v.to_string()).unwrap_or_default();
        stdin.write_all(payload.as_bytes()).expect("write oracle stdin");
    }
    let output = child.wait_with_output().expect("wait for status_readers_a_oracle driver");
    assert!(
        output.status.success(),
        "oracle op {op} exited non-zero — stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    serde_json::from_str(stdout.trim())
        .unwrap_or_else(|e| panic!("oracle op {op}: could not parse stdout {stdout:?}: {e}"))
}

fn write_file(path: &Path, content: &str) {
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

fn bee_dir(root: &Path) -> PathBuf {
    root.join(".bee")
}

// ─── host-real fixture (queen-bench --generate, prebuilt binary as-is) ─────

fn queen_bench_bin() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for _ in 0..12 {
        let candidate = dir.join("crates").join("target").join("debug").join(if cfg!(windows) {
            "queen-bench.exe"
        } else {
            "queen-bench"
        });
        if candidate.exists() {
            return candidate;
        }
        if !dir.pop() {
            break;
        }
    }
    panic!(
        "status_readers_a: could not locate a prebuilt queen-bench binary walking ancestors from {} \
         — this cell uses the CURRENT compiled queen-bench binary as a fixed fixture-generation artifact \
         (rust-port-19 owns queen-bench/* this wave) rather than rebuilding it itself; build the workspace \
         once (`cargo build --manifest-path crates/Cargo.toml -p queen-bench`) if it is genuinely missing.",
        env!("CARGO_MANIFEST_DIR")
    );
}

/// Generates a host-real-shaped `.bee` store at the D5 pinned floors via
/// the prebuilt `queen-bench --generate` binary. Panics loudly on a
/// generation failure.
fn host_real_fixture() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    let output = Command::new(queen_bench_bin())
        .arg("--generate")
        .arg("--out")
        .arg(dir.path())
        .output()
        .expect("failed to spawn queen-bench --generate");
    assert!(
        output.status.success(),
        "queen-bench --generate failed — stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    dir
}

// ─── host-real fixture: one test per reader, oracle-diffed ─────────────────

#[test]
fn status_readers_a_backlog_counts_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = cells_root_backlog(fixture.path());
    let mjs_result = run_oracle("backlog-counts", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

fn cells_root_backlog(root: &Path) -> Value {
    bee_core::backlog::read_backlog_counts(root).unwrap_or(Value::Null)
}

#[test]
fn status_readers_a_capture_queue_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = bee_core::capture::capture_queue(fixture.path());
    let mjs_result = run_oracle("capture-queue", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_active_decisions_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result: Value = json!(bee_core::decisions::active_decisions(fixture.path(), None, false));
    let mjs_result = run_oracle("active-decisions", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_archived_totals_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = cells::archived_totals(fixture.path());
    let mjs_result = run_oracle("archived-totals", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_ready_cells_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result: Value = json!(cells::ready_cells(fixture.path(), None));
    let mjs_result = run_oracle("ready-cells", fixture.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_scribing_debt_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = cells::scribing_debt(fixture.path(), None, None);
    let mjs_result = run_oracle("scribing-debt", fixture.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_global_scribing_debt_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = cells::global_scribing_debt(fixture.path());
    let mjs_result = run_oracle("global-scribing-debt", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_tier_mix_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result = cells::tier_mix(fixture.path(), None);
    let mjs_result = run_oracle("tier-mix", fixture.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
}

#[test]
fn status_readers_a_ceiling_scarcity_matches_mjs_on_host_real_fixture() {
    let fixture = host_real_fixture();
    let rust_result: Value = cells::ceiling_scarcity_warning(fixture.path()).unwrap_or(Value::Null);
    let mjs_result = run_oracle("ceiling-scarcity", fixture.path(), None);
    assert_eq!(rust_result, mjs_result);
}

// ─── edge fixture: empty store, every reader agrees with mjs ───────────────

#[test]
fn status_readers_a_all_readers_agree_with_mjs_on_empty_store() {
    let dir = tempfile::tempdir().expect("tempdir");
    // Not even `.bee/` exists yet — the maximally-empty case every reader's
    // fail-open contract must survive.
    let root = dir.path();

    let cases: Vec<(&str, Option<Value>, Value)> = vec![
        ("backlog-counts", None, cells_root_backlog(root)),
        ("capture-queue", None, bee_core::capture::capture_queue(root)),
        ("active-decisions", Some(json!({})), json!(bee_core::decisions::active_decisions(root, None, false))),
        ("archived-totals", None, cells::archived_totals(root)),
        ("ready-cells", Some(json!({})), json!(cells::ready_cells(root, None))),
        ("scribing-debt", Some(json!({})), cells::scribing_debt(root, None, None)),
        ("global-scribing-debt", None, cells::global_scribing_debt(root)),
        ("tier-mix", Some(json!({})), cells::tier_mix(root, None)),
        ("ceiling-scarcity", None, cells::ceiling_scarcity_warning(root).unwrap_or(Value::Null)),
    ];

    for (op, args, rust_result) in cases {
        let mjs_result = run_oracle(op, root, args);
        assert_eq!(rust_result, mjs_result, "reader {op} diverged from mjs on an empty store");
    }
}

// ─── edge fixture: corrupt/truncated jsonl tails ────────────────────────────
// Table-driven over the SAME 7 corruption shapes `fsutil_oracle.rs`
// established (test-economy D3/D5: reused, not reinvented), applied to each
// of the three jsonl-backed readers this cell owns.

fn corruption_cases() -> Vec<(&'static str, &'static str)> {
    vec![
        ("truncated_last_line", "TRUNC"),
        ("no_trailing_newline", "NO_TRAILING_NEWLINE"),
        ("blank_lines_interspersed", "BLANK_LINES"),
        ("invalid_json_in_middle", "INVALID_MIDDLE"),
        ("crlf_line_endings", "CRLF"),
        ("leading_bom_first_line_corrupt", "BOM_FIRST"),
        ("empty_file", "EMPTY"),
    ]
}

fn apply_corruption(shape: &str, valid_lines: &[String]) -> Vec<u8> {
    match shape {
        "TRUNC" => {
            let mut body = valid_lines.join("\n");
            body.push_str("\n{\"broken");
            body.into_bytes()
        }
        "NO_TRAILING_NEWLINE" => valid_lines.join("\n").into_bytes(),
        "BLANK_LINES" => {
            let mut out = String::new();
            for line in valid_lines {
                out.push_str(line);
                out.push_str("\n\n   \n");
            }
            out.into_bytes()
        }
        "INVALID_MIDDLE" => {
            let mut out = String::new();
            for (i, line) in valid_lines.iter().enumerate() {
                out.push_str(line);
                out.push('\n');
                if i == 0 {
                    out.push_str("not json at all\n");
                }
            }
            out.into_bytes()
        }
        "CRLF" => {
            let mut out = String::new();
            for line in valid_lines {
                out.push_str(line);
                out.push_str("\r\n");
            }
            out.into_bytes()
        }
        "BOM_FIRST" => {
            let mut out: Vec<u8> = vec![0xEF, 0xBB, 0xBF];
            out.extend_from_slice(valid_lines.join("\n").as_bytes());
            out.push(b'\n');
            out
        }
        "EMPTY" => Vec::new(),
        other => panic!("unknown corruption shape {other}"),
    }
}

#[test]
fn status_readers_a_backlog_counts_matches_mjs_on_corrupt_backlog_tail() {
    let valid_lines = vec![
        json!({"kind":"pbi","event":"add","id":"p-1","title":"one","status":"proposed"}).to_string(),
        json!({"kind":"pbi","event":"add","id":"p-2","title":"two","status":"in-flight"}).to_string(),
    ];
    for (name, shape) in corruption_cases() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_file(
            &bee_dir(dir.path()).join("backlog.jsonl"),
            &String::from_utf8_lossy(&apply_corruption(shape, &valid_lines)),
        );
        let rust_result = cells_root_backlog(dir.path());
        let mjs_result = run_oracle("backlog-counts", dir.path(), None);
        assert_eq!(rust_result, mjs_result, "case {name}: readBacklogCounts diverged from mjs");
    }
}

#[test]
fn status_readers_a_active_decisions_matches_mjs_on_corrupt_decisions_tail() {
    let valid_lines = vec![
        json!({"id":"d-1","type":"decide","date":"2026-01-01T00:00:00.000Z","decision":"one"}).to_string(),
        json!({"id":"d-2","type":"decide","date":"2026-01-02T00:00:00.000Z","decision":"two"}).to_string(),
    ];
    for (name, shape) in corruption_cases() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_file(
            &bee_dir(dir.path()).join("decisions.jsonl"),
            &String::from_utf8_lossy(&apply_corruption(shape, &valid_lines)),
        );
        let rust_result: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, false));
        let mjs_result = run_oracle("active-decisions", dir.path(), Some(json!({})));
        assert_eq!(rust_result, mjs_result, "case {name}: activeDecisions diverged from mjs");
    }
}

#[test]
fn status_readers_a_capture_queue_matches_mjs_on_corrupt_capture_tail() {
    let valid_lines = vec![
        json!({"kind":"stub","id":"s-1","at":"2026-01-01T00:00:00.000Z","outcome":"one","dids":[],"area":null,"files":[],"lane":null}).to_string(),
        json!({"kind":"stub","id":"s-2","at":"2026-01-02T00:00:00.000Z","outcome":"two","dids":[],"area":null,"files":[],"lane":null}).to_string(),
    ];
    for (name, shape) in corruption_cases() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_file(
            &bee_dir(dir.path()).join("capture-queue.jsonl"),
            &String::from_utf8_lossy(&apply_corruption(shape, &valid_lines)),
        );
        let rust_result = bee_core::capture::capture_queue(dir.path());
        let mjs_result = run_oracle("capture-queue", dir.path(), None);
        assert_eq!(rust_result, mjs_result, "case {name}: captureQueue diverged from mjs");
    }
}

// ─── edge fixture: unknown extra fields survive ─────────────────────────────

#[test]
fn status_readers_a_active_decisions_preserves_unknown_fields() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_file(
        &bee_dir(dir.path()).join("decisions.jsonl"),
        &format!(
            "{}\n",
            json!({
                "id": "d-1", "type": "decide", "date": "2026-01-01T00:00:00.000Z",
                "decision": "kept", "future_field": "still here",
                "nested": {"a": 1, "b": [1, 2, 3]}
            })
        ),
    );
    let rust_result: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, false));
    let mjs_result = run_oracle("active-decisions", dir.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
    assert_eq!(rust_result[0]["future_field"], json!("still here"));
    assert_eq!(rust_result[0]["nested"], json!({"a": 1, "b": [1, 2, 3]}));
}

#[test]
fn status_readers_a_capture_queue_preserves_unknown_stub_fields() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_file(
        &bee_dir(dir.path()).join("capture-queue.jsonl"),
        &format!(
            "{}\n",
            json!({
                "kind": "stub", "id": "s-1", "at": "2026-01-01T00:00:00.000Z",
                "outcome": "kept", "dids": [], "area": null, "files": [], "lane": null,
                "source": "mined", "future_field": {"deep": "value"}
            })
        ),
    );
    let rust_result = bee_core::capture::capture_queue(dir.path());
    let mjs_result = run_oracle("capture-queue", dir.path(), None);
    assert_eq!(rust_result, mjs_result);
    assert_eq!(rust_result["stubs"][0]["future_field"], json!({"deep": "value"}));
}

#[test]
fn status_readers_a_ready_cells_preserves_unknown_cell_fields() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_file(
        &bee_dir(dir.path()).join("cells").join("rp-a-01.json"),
        &json!({
            "id": "rp-a-01", "feature": "feat-a", "status": "open",
            "deps": [], "files": [], "future_field": "kept-as-is",
            "must_haves": {"truths": ["x"]}
        })
        .to_string(),
    );
    let rust_result: Value = json!(cells::ready_cells(dir.path(), Some("feat-a")));
    let mjs_result = run_oracle("ready-cells", dir.path(), Some(json!({"feature": "feat-a"})));
    assert_eq!(rust_result, mjs_result);
    assert_eq!(rust_result[0]["future_field"], json!("kept-as-is"));
}

// ─── decisions logic: supersession, redaction, tag overlay, archive union ──

fn write_decisions(root: &Path, events: &[Value]) {
    let body: String = events.iter().map(|e| format!("{}\n", e)).collect();
    write_file(&bee_dir(root).join("decisions.jsonl"), &body);
}

#[test]
fn status_readers_a_active_decisions_excludes_superseded_and_redacted() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_decisions(
        dir.path(),
        &[
            json!({"id": "d-1", "type": "decide", "date": "2026-01-01T00:00:00.000Z", "decision": "one"}),
            json!({"id": "d-2", "type": "decide", "date": "2026-01-02T00:00:00.000Z", "decision": "two"}),
            json!({"id": "d-3", "type": "supersede", "date": "2026-01-03T00:00:00.000Z", "supersedes": "d-1", "decision": "one, revised"}),
            json!({"id": "d-4", "type": "decide", "date": "2026-01-04T00:00:00.000Z", "decision": "three"}),
            json!({"id": "d-5", "type": "redact", "date": "2026-01-05T00:00:00.000Z", "redacts": "d-2"}),
        ],
    );
    let rust_result: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, false));
    let mjs_result = run_oracle("active-decisions", dir.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
    let ids: Vec<String> = rust_result.as_array().unwrap().iter().map(|e| e["id"].as_str().unwrap().to_string()).collect();
    // d-1 superseded (excluded), d-2 redacted (excluded); d-3 (the
    // supersede action itself) and d-4 remain, newest first.
    assert_eq!(ids, vec!["d-4".to_string(), "d-3".to_string()]);
}

#[test]
fn status_readers_a_active_decisions_tag_overlay_replaces_tags_and_scope() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_decisions(
        dir.path(),
        &[
            json!({"id": "d-1", "type": "decide", "date": "2026-01-01T00:00:00.000Z", "decision": "one", "tags": ["old"], "scope": "repo"}),
            json!({"id": "tag-1", "type": "tag", "date": "2026-01-02T00:00:00.000Z", "target": "d-1", "tags": ["new", "shiny"]}),
            json!({"id": "tag-2", "type": "tag", "date": "2026-01-03T00:00:00.000Z", "target": "d-1", "tags": [], "scope": "feature-x"}),
        ],
    );
    let rust_result: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, false));
    let mjs_result = run_oracle("active-decisions", dir.path(), Some(json!({})));
    assert_eq!(rust_result, mjs_result);
    // The LATEST tag event (tag-2) wins: tags replaced with [] (still an
    // explicit override, even though empty), scope replaced with
    // "feature-x".
    assert_eq!(rust_result[0]["id"], json!("d-1"));
    assert_eq!(rust_result[0]["tags"], json!([]));
    assert_eq!(rust_result[0]["scope"], json!("feature-x"));
}

#[test]
fn status_readers_a_active_decisions_all_true_unions_archive_with_active_precedence() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_decisions(
        dir.path(),
        &[json!({"id": "d-2", "type": "decide", "date": "2026-01-02T00:00:00.000Z", "decision": "active copy wins"})],
    );
    write_file(
        &bee_dir(dir.path()).join("decisions-archive.jsonl"),
        &format!(
            "{}\n{}\n",
            json!({"id": "d-1", "type": "decide", "date": "2026-01-01T00:00:00.000Z", "decision": "archived only"}),
            json!({"id": "d-2", "type": "decide", "date": "2026-01-02T00:00:00.000Z", "decision": "archived copy loses"}),
        ),
    );
    let rust_default: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, false));
    let mjs_default = run_oracle("active-decisions", dir.path(), Some(json!({})));
    assert_eq!(rust_default, mjs_default);
    assert_eq!(rust_default.as_array().unwrap().len(), 1, "default (all:false) never reads the archive");

    let rust_all: Value = json!(bee_core::decisions::active_decisions(dir.path(), None, true));
    let mjs_all = run_oracle("active-decisions", dir.path(), Some(json!({"all": true})));
    assert_eq!(rust_all, mjs_all);
    let by_id: std::collections::HashMap<String, Value> = rust_all
        .as_array()
        .unwrap()
        .iter()
        .map(|e| (e["id"].as_str().unwrap().to_string(), e.clone()))
        .collect();
    assert_eq!(by_id.len(), 2);
    assert_eq!(by_id["d-2"]["decision"], json!("active copy wins"), "the active store's copy must win the union");
}

// ─── cells logic: deps gating, scribing-debt orphan sweep, tier mix ────────

fn write_cell(root: &Path, id: &str, body: &Value) {
    write_file(&bee_dir(root).join("cells").join(format!("{id}.json")), &body.to_string());
}

#[test]
fn status_readers_a_ready_cells_excludes_cells_with_uncapped_deps() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_cell(dir.path(), "rp-01", &json!({"id": "rp-01", "feature": "f", "status": "capped", "deps": [], "files": []}));
    write_cell(dir.path(), "rp-02", &json!({"id": "rp-02", "feature": "f", "status": "open", "deps": ["rp-01"], "files": []}));
    write_cell(dir.path(), "rp-03", &json!({"id": "rp-03", "feature": "f", "status": "open", "deps": ["rp-99"], "files": []}));
    write_cell(dir.path(), "rp-04", &json!({"id": "rp-04", "feature": "f", "status": "open", "deps": [], "files": []}));

    let rust_result: Value = json!(cells::ready_cells(dir.path(), Some("f")));
    let mjs_result = run_oracle("ready-cells", dir.path(), Some(json!({"feature": "f"})));
    assert_eq!(rust_result, mjs_result);
    let ids: Vec<String> = rust_result.as_array().unwrap().iter().map(|c| c["id"].as_str().unwrap().to_string()).collect();
    // rp-02: dep rp-01 is capped -> ready. rp-03: dep rp-99 doesn't exist ->
    // not ready. rp-04: no deps -> ready.
    assert_eq!(ids, vec!["rp-02".to_string(), "rp-04".to_string()]);
}

#[test]
fn status_readers_a_tier_mix_and_ceiling_scarcity_match_mjs() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_file(&bee_dir(dir.path()).join("state.json"), &json!({"phase": "swarming", "feature": "f"}).to_string());
    write_cell(dir.path(), "rp-01", &json!({"id": "rp-01", "feature": "f", "status": "capped", "tier": "ceiling", "deps": [], "files": []}));
    write_cell(dir.path(), "rp-02", &json!({"id": "rp-02", "feature": "f", "status": "capped", "tier": "ceiling", "deps": [], "files": []}));
    write_cell(dir.path(), "rp-03", &json!({"id": "rp-03", "feature": "f", "status": "capped", "tier": "generation", "deps": [], "files": []}));
    write_cell(dir.path(), "rp-04", &json!({"id": "rp-04", "feature": "f", "status": "capped", "tier": "extraction", "deps": [], "files": []}));
    write_cell(dir.path(), "rp-05", &json!({"id": "rp-05", "feature": "f", "status": "capped", "deps": [], "files": []}));

    let rust_mix = cells::tier_mix(dir.path(), Some("f"));
    let mjs_mix = run_oracle("tier-mix", dir.path(), Some(json!({"feature": "f"})));
    assert_eq!(rust_mix, mjs_mix);
    assert_eq!(rust_mix["counts"]["ceiling"], json!(2));
    assert_eq!(rust_mix["tiered"], json!(4));

    // 2/4 = 50% ceiling share > CEILING_MAX_SHARE (40%), and tiered (4) >=
    // SCARCITY_MIN_TIERED (3) -> a warning fires.
    let rust_warning: Value = cells::ceiling_scarcity_warning(dir.path()).unwrap_or(Value::Null);
    let mjs_warning = run_oracle("ceiling-scarcity", dir.path(), None);
    assert_eq!(rust_warning, mjs_warning);
    assert_eq!(rust_warning["pct"], json!(50));
}

#[test]
fn status_readers_a_scribing_debt_orphan_sweep_across_features() {
    let dir = tempfile::tempdir().expect("tempdir");
    // Feature "orphan-f": a capped behavior_change cell, no scribing-run
    // evidence anywhere -> orphaned.
    write_cell(
        dir.path(),
        "rp-orphan-1",
        &json!({
            "id": "rp-orphan-1", "feature": "orphan-f", "status": "capped", "deps": [], "files": [],
            "trace": {"behavior_change": true, "capped_at": "2026-01-10T00:00:00.000Z"}
        }),
    );
    // Feature "synced-f": a capped behavior_change cell, WITH a ledger
    // entry after its capped_at -> not orphaned.
    write_cell(
        dir.path(),
        "rp-synced-1",
        &json!({
            "id": "rp-synced-1", "feature": "synced-f", "status": "capped", "deps": [], "files": [],
            "trace": {"behavior_change": true, "capped_at": "2026-01-10T00:00:00.000Z"}
        }),
    );
    write_file(
        &bee_dir(dir.path()).join("logs").join("scribing-runs.jsonl"),
        &format!("{}\n", json!({"ts": "2026-01-11T00:00:00.000Z", "feature": "synced-f", "areas": ["x"]})),
    );
    // Feature "not-behavior-f": capped but NOT a behavior_change cell ->
    // never counted at all.
    write_cell(
        dir.path(),
        "rp-plain-1",
        &json!({
            "id": "rp-plain-1", "feature": "not-behavior-f", "status": "capped", "deps": [], "files": [],
            "trace": {"behavior_change": false, "capped_at": "2026-01-10T00:00:00.000Z"}
        }),
    );

    let rust_global = cells::global_scribing_debt(dir.path());
    let mjs_global = run_oracle("global-scribing-debt", dir.path(), None);
    assert_eq!(rust_global, mjs_global);
    assert_eq!(rust_global["count"], json!(1));
    assert_eq!(rust_global["features"], json!([{"feature": "orphan-f", "cells": ["rp-orphan-1"]}]));

    // scribingDebt(root, {feature: "orphan-f"}) with no sinceTs override
    // derives the same threshold (0, since bestScribingStampMs finds
    // nothing) and reports the same cell as debt.
    let rust_debt = cells::scribing_debt(dir.path(), Some("orphan-f"), None);
    let mjs_debt = run_oracle("scribing-debt", dir.path(), Some(json!({"feature": "orphan-f"})));
    assert_eq!(rust_debt, mjs_debt);
    assert_eq!(rust_debt["cells"], json!(["rp-orphan-1"]));

    // scribingDebt for "synced-f" is empty: the ledger stamp postdates the
    // cell's capped_at.
    let rust_synced = cells::scribing_debt(dir.path(), Some("synced-f"), None);
    let mjs_synced = run_oracle("scribing-debt", dir.path(), Some(json!({"feature": "synced-f"})));
    assert_eq!(rust_synced, mjs_synced);
    assert_eq!(rust_synced["count"], json!(0));

    // An explicit sinceTs override in the far future clears even the
    // orphaned feature's debt.
    let far_future_ms = 4_000_000_000_000i64; // year ~2096, well past capped_at
    let rust_future = cells::scribing_debt(dir.path(), Some("orphan-f"), Some(far_future_ms));
    let mjs_future = run_oracle("scribing-debt", dir.path(), Some(json!({"feature": "orphan-f", "sinceTs": far_future_ms})));
    assert_eq!(rust_future, mjs_future);
    assert_eq!(rust_future["count"], json!(0));
}

#[test]
fn status_readers_a_archived_totals_sums_and_tolerates_partial_entries() {
    let dir = tempfile::tempdir().expect("tempdir");
    write_file(
        &bee_dir(dir.path()).join("cells").join("archive").join("summary.json"),
        &json!({
            "feat-a": {"capped": 5, "dropped": 1, "archived_at": "2026-01-01T00:00:00.000Z"},
            "feat-b": {"capped": 3, "dropped": 0, "archived_at": "2026-01-02T00:00:00.000Z"},
            "feat-c": {"dropped": 2},
        })
        .to_string(),
    );
    let rust_result = cells::archived_totals(dir.path());
    let mjs_result = run_oracle("archived-totals", dir.path(), None);
    assert_eq!(rust_result, mjs_result);
    assert_eq!(rust_result, json!({"capped": 8, "dropped": 3, "total": 11}));
}
